version: "3.9"

services:
  # === AUTH SERVICE ===
  auth-service:
    image: ${ACR_LOGIN_SERVER}/pettrack-auth-service:latest
    container_name: auth_service
    env_file:
      - ./services/auth-service/.env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - backend

  # === PETS SERVICE ===
  pets-service:
    image: ${ACR_LOGIN_SERVER}/pettrack-pets-service:latest
    container_name: pets_service
    env_file:
      - ./services/pets-service/.env
    ports:
      - "8001:8000"
    restart: always
    networks:
      - backend

  # === APPOINTMENTS SERVICE ===
  appointment-service:
    image: ${ACR_LOGIN_SERVER}/pettrack-appointment-service:latest
    container_name: appointment_service
    env_file:
      - ./services/appointment-service/.env
    ports:
      - "8002:8000"
    restart: always
    networks:
      - backend

  # === REWARDS SERVICE ===
  rewards-service:
    image: ${ACR_LOGIN_SERVER}/pettrack-rewards-service:latest
    container_name: rewards_service
    env_file:
      - ./services/rewards-service/.env
    ports:
      - "8004:8000"
    restart: always
    networks:
      - backend

  # === POSTCONSULT SERVICE ===
  postconsult-service:
    image: ${ACR_LOGIN_SERVER}/pettrack-postconsult-service:latest
    container_name: postconsult_service
    env_file:
      - ./services/postconsult-service/.env
    ports:
      - "8005:8000"
    restart: always
    networks:
      - backend

  # === API GATEWAY ===
  api-gateway:
    image: ${ACR_LOGIN_SERVER}/pettrack-api-gateway:latest
    container_name: api_gateway
    ports:
      - "8003:8003"
    env_file:
      - ./services/api-gateway/.env
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8000"
      PETS_SERVICE_URL: "http://pets-service:8000"
      APPOINTMENTS_SERVICE_URL: "http://appointment-service:8000"
      REWARDS_SERVICE_URL: "http://rewards-service:8000"
      POSTCONSULT_SERVICE_URL: "http://postconsult-service:8000"
    depends_on:
      - auth-service
      - pets-service
      - appointment-service
      - rewards-service
      - postconsult-service
    restart: always
    networks:
      - backend

  # === WEB CLIENT ===
  client:
    image: ${ACR_LOGIN_SERVER}/pettrack-web-client:latest
    container_name: web_client
    ports:
      - "80:80"
    env_file:
      - ./clients/web-client/.env
    depends_on:
      - api-gateway
    environment:
      VITE_API_GATEWAY: "http://api-gateway:8003"
      VITE_API_APIM_URL: "https://pettrack-apim.azure-api.net"
    restart: always
    networks:
      - backend

# === NETWORKS ===
networks:
  backend:
    driver: bridge

# === VOLUMES ===
volumes:
  auth_data:
  pets_data:
  appointments_data:
  rewards_data:
  postconsult_data:
